spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Hjy3.1415926
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.jyh.springbootadvanced: debug
  file: log/my.log